main: com.github.dawsonvilamaa.nationsandvillagesplugin.Main
name: NationsAndVillagesPlugin
version: 1.0
api-version: 1.13
author: Dawson Vilamaa
description: Allows players to create nations and villages to rule over and adds functionality to villages and villagers
commands:
  balance:
    aliases: [bal, money]
    description: shows you how much money you have
    usage: /balance
    permission: NationsAndVillages.money
    permission-message: You don't have permission to use that command
  nation:
    aliases: [nations, n]
    description: creates a nation
    usage: /nation <autoclaim | autounclaim | claim | create | demote | enemy | exile | info | invite | join | leave | list | perms | promote | rename | unclaim> [name]
    permission: NationsAndVillages.nation
    permission-message: You don't have permission to use that command
  sell:
    description: sell the item in your hand to give to a merchant
    usage: /sell <price | cancel>
    permission: NationsAndVillages.sell
    permission-message: You don't have permission to use that command